"""Se añadio el atributo letra a Opciones de preguntas para mejor organizacion

Revision ID: 2f62e7a937fa
Revises: d3aa9136a91e
Create Date: 2025-10-06 15:19:14.011172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f62e7a937fa'
down_revision = 'd3aa9136a91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opciones_pregunta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('letra', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opciones_pregunta', schema=None) as batch_op:
        batch_op.drop_column('letra')

    # ### end Alembic commands ###
