"""Correccion del modelo Preguntas

Revision ID: 623119026a4f
Revises: 7b178044a84e
Create Date: 2025-10-01 13:50:26.496411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623119026a4f'
down_revision = '7b178044a84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('context_img', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.drop_column('context_img')
        batch_op.drop_column('context')

    # ### end Alembic commands ###
