"""Creacion de tablas iniciales

Revision ID: 7b178044a84e
Revises: 
Create Date: 2025-09-17 23:21:25.637954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b178044a84e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tematicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_tematica', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.String(length=50), nullable=False),
    sa.Column('apellidos', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('preguntas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tematicas', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_tematicas'], ['tematicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pruebas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_tematica', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_tematica'], ['tematicas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opciones_pregunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_preguntas', sa.Integer(), nullable=False),
    sa.Column('texto_opcion', sa.String(length=250), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_preguntas'], ['preguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_usuario_prueba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pruebas', sa.Integer(), nullable=False),
    sa.Column('id_preguntas', sa.Integer(), nullable=False),
    sa.Column('id_opciones_pregunta', sa.Integer(), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_opciones_pregunta'], ['opciones_pregunta.id'], ),
    sa.ForeignKeyConstraint(['id_preguntas'], ['preguntas.id'], ),
    sa.ForeignKeyConstraint(['id_pruebas'], ['pruebas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestas_usuario_prueba')
    op.drop_table('opciones_pregunta')
    op.drop_table('pruebas')
    op.drop_table('preguntas')
    op.drop_table('users')
    op.drop_table('tematicas')
    # ### end Alembic commands ###
