"""Añadir campo n_pregunta para poder evitar preguntas iguales a la hora de añadirlas a la base de datos

Revision ID: 802c6f187df1
Revises: 623119026a4f
Create Date: 2025-10-01 14:18:02.867000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802c6f187df1'
down_revision = '623119026a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('n_pregunta', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.drop_column('n_pregunta')

    # ### end Alembic commands ###
