"""Cositas

Revision ID: b3f9919ae2e5
Revises: 2f62e7a937fa
Create Date: 2025-10-22 20:55:19.105849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f9919ae2e5'
down_revision = '2f62e7a937fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pruebas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seleccion_usuario', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pruebas', schema=None) as batch_op:
        batch_op.drop_column('seleccion_usuario')

    # ### end Alembic commands ###
