"""que desastre

Revision ID: d3aa9136a91e
Revises: 42f6522141ab
Create Date: 2025-10-02 14:57:57.612872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3aa9136a91e'
down_revision = '42f6522141ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.drop_column('n_pregunta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('n_pregunta', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
