"""Cambiadn oel tipo de dato de enunciado y context a Text para que abarque mas palabras

Revision ID: f192257f67e4
Revises: 802c6f187df1
Create Date: 2025-10-02 14:42:17.909145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f192257f67e4'
down_revision = '802c6f187df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.alter_column('enunciado',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('context',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('context_img',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.alter_column('context_img',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('context',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('enunciado',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
